config:
  url_90 : http://47.95.240.88:9621
  url_IDC: https://mmmj.igamesofficial.com:8101
  openid: enNvbHRqeS9TQXFrZU9Camg3TExDQT09
  momoids: 19090013
  server_id: 10003
  num: 1000000
  product_id: 99003
  level: 250
  exp: 800
  while_adventure: 500
  while_artifact_upStar: 51
  challenger: OEd2VkZwempqREMrK01xNFpsKy92QT09